language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install matplotlib
  - pip install sklearn
  - pip install pyfiglet
# command to run tests
script:
  - if python my_script.py; then echo 1; else echo 0; fi
  - python my_script.py hwk4_data/diabetes.data
  - python my_script.py hwk4_data/diabetes.data -p
  - if python my_script.py -p; then echo 1; else echo 0; fi
  - python my_script.py hwk4_data/diabetes.data -s age
  - python my_script.py hwk4_data/diabetes.data -s sex
  - python my_script.py hwk4_data/diabetes.data -s bmi
  - python my_script.py hwk4_data/diabetes.data -s map
  - python my_script.py hwk4_data/diabetes.data -s tc
  - python my_script.py hwk4_data/diabetes.data -s ldl
  - python my_script.py hwk4_data/diabetes.data -s hdl
  - python my_script.py hwk4_data/diabetes.data -s tch
  - python my_script.py hwk4_data/diabetes.data -s ltg
  - python my_script.py hwk4_data/diabetes.data -s glu
  - python my_script.py hwk4_data/diabetes.data -s y
  - if python my_script.py -s age; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -s adil; then echo 1; else echo 0; fi
  - python my_script.py hwk4_data/diabetes.data -i age bmi 0.1
  - if python my_script.py -i age bmi 0.1; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i age age; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i age age 0.1; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i age adil 0.1; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i adil age 0.1; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i age bmi 1; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i age sex 0.1; then echo 1; else echo 0; fi
  - if python my_script.py hwk4_data/diabetes.data -i sex age 0.1; then echo 1; else echo 0; fi
  - pytest
  # week8
  - python week8.py
  # week9
  - python week9.py
